# Generated by Django 3.2 on 2021-06-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ('created_time',), 'verbose_name': 'Advertisement', 'verbose_name_plural': 'Advertisements'},
        ),
    ]
