# Generated by Django 3.2 on 2021-06-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_auto_20210623_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='is_available',
        ),
    ]
