# Generated by Django 3.2 on 2021-06-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_remove_advertisement_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='is available'),
        ),
    ]
