# Generated by Django 3.2 on 2021-06-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0008_advertisement_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementimages',
            options={'verbose_name': 'Advertisement Image', 'verbose_name_plural': 'Advertisement Images'},
        ),
        migrations.AlterModelTable(
            name='advertisementimages',
            table='advertisement_image',
        ),
    ]
