# Generated by Django 3.2 on 2021-06-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_auto_20210623_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/images/', verbose_name='image'),
        ),
    ]
