# Generated by Django 3.2 on 2021-06-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0010_alter_advertisementimages_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='uuid',
            new_name='upc',
        ),
    ]
