# Generated by Django 3.2 on 2021-06-24 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0012_auto_20210624_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=django.utils.timezone.now, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
