# Generated by Django 3.2 on 2021-07-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0013_city_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='is_available',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'draft'), (1, 'accepted'), (2, 'not approved')], default=0, verbose_name='status'),
        ),
    ]
