# Generated by Django 3.2 on 2021-08-04 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0015_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('promotion_type', models.PositiveSmallIntegerField(choices=[(0, 'instantaneous'), (1, 'ladder')], verbose_name='promotion type')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='advertisement.advertisement', verbose_name='advertisement')),
            ],
        ),
    ]
