# Generated by Django 3.2 on 2021-08-04 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisement', '0016_advertisementpromotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementpromotion',
            options={'verbose_name': 'AdvertisementPromotion', 'verbose_name_plural': 'AdvertisementPromotions'},
        ),
        migrations.AddField(
            model_name='advertisementpromotion',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='advertisementpromotion',
            table='advertisement_promotion',
        ),
        migrations.CreateModel(
            name='AdvertisementEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='advertisement.advertisement', verbose_name='advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'ّAdvertisementEngagement',
                'verbose_name_plural': 'ّAdvertisementEngagements',
                'db_table': 'aAdvertisement_engagement',
            },
        ),
    ]
