# Generated by Django 3.2 on 2021-08-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0017_auto_20210804_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementengagement',
            options={'verbose_name': 'AdvertisementEngagement', 'verbose_name_plural': 'AdvertisementEngagements'},
        ),
        migrations.DeleteModel(
            name='AdvertisementPromotion',
        ),
    ]
