# Generated by Django 3.2 on 2021-08-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0018_auto_20210804_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Advertisement', 'verbose_name_plural': 'Advertisements'},
        ),
    ]
