# Generated by Django 3.2 on 2021-08-04 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisement', '0019_alter_advertisement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementengagement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
