# Generated by Django 3.2 on 2021-08-24 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0021_auto_20210817_1548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvertisementImages',
            new_name='AdvertisementImage',
        ),
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ('-ad_time', '-created_time'), 'verbose_name': 'Advertisement', 'verbose_name_plural': 'Advertisements'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='type',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='advertisementattribute',
            name='advertisement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='advertisement.category'),
        ),
        migrations.DeleteModel(
            name='AdvertisementType',
        ),
    ]
