# Generated by Django 3.2 on 2021-08-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0022_auto_20210824_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='type',
        ),
    ]
