# Generated by Django 3.2 on 2021-08-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0023_remove_advertisement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementattribute',
            name='name',
            field=models.CharField(max_length=32, verbose_name='name'),
        ),
    ]
