# Generated by Django 3.2 on 2021-08-04 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisement', '0018_auto_20210804_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('name', models.SmallIntegerField(choices=[(1, 'instantaneous'), (2, 'ladder')], verbose_name='name')),
                ('price', models.IntegerField(verbose_name='price')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvertisementPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='advertisement.advertisement', verbose_name='advertisement')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='promotion.promotion', verbose_name='promotion type')),
            ],
            options={
                'verbose_name': 'AdvertisementPromotion',
                'verbose_name_plural': 'AdvertisementPromotions',
                'db_table': 'advertisement_promotion',
            },
        ),
    ]
